import { useEffect, useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { BellRing, CheckCircle2, Eye, Filter, History, Search, Send, Smartphone, X } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ModulePageHeader } from "@/components/shared/ModulePageHeader";
import { InventoryReminderCard } from "@/components/admin/InventoryReminderCard";
import { formatCurrency, formatDate, shopStore, useShopStore } from "@/lib/shop-store";
import { sendWhatsAppBatch, type WhatsAppRecipient } from "@/lib/whatsapp";
import type { Customer, CustomerLedgerEntry } from "@/types/business";

const dueTemplate = `Hello {name},\n\nHere is your due overview from Shree Sawariya Agro Agency.\n\n{records}\n\nTotal due: {totalDue}\n\nThank you.`;
type FilterState = { query:string; village:string; minDue:string; maxDue:string; purchaseFrom:string; purchaseTo:string; dueOnly:boolean; whatsappOnly:boolean };
const initialFilters:FilterState={query:"",village:"all",minDue:"",maxDue:"",purchaseFrom:"",purchaseTo:"",dueOnly:true,whatsappOnly:true};

export const Route=createFileRoute("/admin/reminders")({head:()=>({meta:[{title:"Reminders & WhatsApp — Admin"},{name:"description",content:"Inventory reminders, existing reminders and customer due reminders through WhatsApp."},{name:"robots",content:"noindex"}]}),component:RemindersPage});

function RemindersPage(){
 const reminders=useShopStore(s=>s.reminders),customers=useShopStore(s=>s.customers),ledger=useShopStore(s=>s.customerLedger),logs=useShopStore(s=>s.reminderLogs);
 const [filters,setFilters]=useState(initialFilters),[selectedIds,setSelectedIds]=useState<Set<string>>(new Set()),[previewCustomer,setPreviewCustomer]=useState<Customer|null>(null),[message,setMessage]=useState(dueTemplate),[sending,setSending]=useState(false),[result,setResult]=useState<{ok:boolean;text:string}|null>(null),[tab,setTab]=useState("send");
 const villages=useMemo(()=>Array.from(new Set(customers.map(c=>c.village).filter(Boolean))).sort(),[customers]);
 const recipients=useMemo<WhatsAppRecipient[]>(()=>customers.map(c=>({id:c.id,name:c.name,mobile:c.mobile,due:c.currentDue,village:c.village,lastPurchase:c.lastPurchase})),[customers]);
 const filteredCustomers=useMemo(()=>{const q=filters.query.trim().toLowerCase(),min=filters.minDue===""?Number.NEGATIVE_INFINITY:Number(filters.minDue),max=filters.maxDue===""?Number.POSITIVE_INFINITY:Number(filters.maxDue);return customers.filter(c=>{const query=!q||`${c.name} ${c.mobile} ${c.village}`.toLowerCase().includes(q),village=filters.village==="all"||c.village===filters.village,due=c.currentDue>=min&&c.currentDue<=max,dueOnly=!filters.dueOnly||c.currentDue>0,wa=!filters.whatsappOnly||Boolean(c.mobile?.trim()),last=c.lastPurchase||"",from=!filters.purchaseFrom||last>=filters.purchaseFrom,to=!filters.purchaseTo||last<=filters.purchaseTo;return query&&village&&due&&dueOnly&&wa&&from&&to})},[customers,filters]);
 const selectedCustomers=useMemo(()=>filteredCustomers.filter(c=>selectedIds.has(c.id)),[filteredCustomers,selectedIds]);
 const selectedDue=selectedCustomers.reduce((sum,c)=>sum+c.currentDue,0);
 const totalReminderAmount=reminders.reduce((sum,r)=>sum+r.dueAmount,0);
 const customReminders=reminders.filter(r=>/custom/i.test(r.title)||/custom/i.test(r.message));
 useEffect(()=>setSelectedIds(current=>{const visible=new Set(filteredCustomers.map(c=>c.id));return new Set(Array.from(current).filter(id=>visible.has(id))) }),[filteredCustomers]);
 const recordsFor=(customer:Customer)=>ledger.filter(e=>e.customerId===customer.id).sort((a,b)=>a.date.localeCompare(b.date));
 const buildOverview=(customer:Customer)=>{const purchases=recordsFor(customer).filter(e=>e.entryType==="purchase"),groups=new Map<string,CustomerLedgerEntry[]>();purchases.forEach(e=>groups.set(e.date,[...(groups.get(e.date)||[]),e]));if(!groups.size)return "No purchase records found.";return Array.from(groups.entries()).map(([date,rows])=>{const lines=rows.map(e=>`• ${e.product||"Purchase"}${e.quantity?` · ${e.quantity}`:""} — ${formatCurrency(e.amount)}`),amount=rows.reduce((s,e)=>s+e.amount,0),paid=rows.reduce((s,e)=>s+e.payment,0),due=rows.reduce((s,e)=>s+e.remainingDue,0);return `${formatDate(date)}\n${lines.join("\n")}\nDay amount: ${formatCurrency(amount)} · Paid: ${formatCurrency(paid)} · Due: ${formatCurrency(due)}`}).join("\n\n")};
 const resolveMessage=(c:Customer)=>message.replaceAll("{name}",c.name).replaceAll("{records}",buildOverview(c)).replaceAll("{totalDue}",formatCurrency(c.currentDue));
 const send=async()=>{const targets=(previewCustomer?[recipients.find(r=>r.id===previewCustomer.id)]:selectedCustomers.map(c=>recipients.find(r=>r.id===c.id))).filter(Boolean) as WhatsAppRecipient[];if(!targets.length){toast.error("Select a customer first.");return}setSending(true);setResult(null);try{const responses=await Promise.all(targets.map(r=>{const c=customers.find(x=>x.id===r.id);return c?sendWhatsAppBatch({kind:"due-reminder",recipients:[r],message:resolveMessage(c)}):Promise.resolve({ok:false,note:"Customer record not found."})}));const sent=responses.filter(r=>r.ok).length,failed=responses.length-sent,text=failed?`${sent} reminder${sent===1?"":"s"} sent, ${failed} failed.`:"Due reminders accepted by Meta Cloud API.";setResult({ok:sent>0,text});sent?toast.success(text):toast.error(text);if(sent){setPreviewCustomer(null);setTab("send")}}catch(e){const text=e instanceof Error?e.message:"WhatsApp delivery failed.";setResult({ok:false,text});toast.error(text)}finally{setSending(false)}};
 return <div className="relative space-y-6">
  <ModulePageHeader crumbs={[{label:"Admin",to:"/admin"},{label:"Reminders"}]} eyebrow="Inventory & customer records" title="Reminders & WhatsApp" description="Inventory stock alerts, existing reminder rules and live Meta WhatsApp due reminders." actions={<Badge variant="outline" className="h-9 rounded-full px-3"><span className="mr-2 size-2 rounded-full bg-emerald-500"/>Live WhatsApp</Badge>}/>
  <div className="grid gap-5 lg:grid-cols-2"><InventoryReminderCard/><Card className="shadow-soft"><CardHeader><CardTitle className="flex items-center gap-2"><BellRing className="size-5 text-primary"/>WhatsApp due reminder</CardTitle><CardDescription>Send a day-by-day purchase and due overview. No account metadata is included.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Metric label="Customers matched" value={String(filteredCustomers.length)} helper={`${selectedCustomers.length} selected`}/><Metric label="Selected due" value={formatCurrency(selectedDue)} helper="Current outstanding"/><Metric label="Message history" value={String(logs.length)} helper="Saved in Supabase"/></div><Button className="w-full rounded-full" onClick={()=>setTab("send")}><Send className="size-4"/>Open due reminders</Button></CardContent></Card></div>
  <div className="grid gap-4 lg:grid-cols-2"><Card className="shadow-soft"><CardHeader><CardTitle>Total Amount Reminder</CardTitle><CardDescription>The existing total-amount reminder remains available; its amount is not inserted into the new due-message template.</CardDescription></CardHeader><CardContent><p className="text-3xl font-semibold">{formatCurrency(totalReminderAmount)}</p><p className="mt-1 text-sm text-muted-foreground">Across {reminders.length} existing reminder rule{reminders.length===1?"":"s"}</p></CardContent></Card><Card className="shadow-soft"><CardHeader><CardTitle>Custom Reminder</CardTitle><CardDescription>The existing custom reminder rule remains available and is not removed by the WhatsApp template change.</CardDescription></CardHeader><CardContent>{customReminders.length?<div className="space-y-2">{customReminders.map(r=><div key={r.id} className="rounded-xl border p-3"><p className="font-medium">{r.title}</p><p className="text-xs text-muted-foreground">{r.message}</p></div>)}</div>:<p className="text-sm text-muted-foreground">No custom reminder rule is currently configured.</p>}</CardContent></Card></div>
  <Card className="shadow-soft"><CardHeader><CardTitle>Existing reminder rules</CardTitle><CardDescription>Original reminder rules stay functional. Toggle active/paused status without affecting the WhatsApp due template.</CardDescription></CardHeader><CardContent className="grid gap-3 lg:grid-cols-2">{reminders.map(reminder=><div key={reminder.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{reminder.title}</p><p className="mt-1 text-xs text-muted-foreground">{reminder.filterSummary}</p></div><Button size="sm" variant={reminder.status==="active"?"default":"outline"} className="rounded-full" onClick={()=>void shopStore.updateReminder(reminder.id,{status:reminder.status==="active"?"paused":"active"})}>{reminder.status==="active"?"Active":"Paused"}</Button></div><div className="mt-3 flex flex-wrap gap-2"><Badge variant="outline" className="rounded-full">{reminder.audience}</Badge><Badge variant="outline" className="rounded-full">{reminder.schedule}</Badge><Badge variant="outline" className="rounded-full">{reminder.channel}</Badge></div><p className="mt-3 text-sm">{reminder.message}</p></div>)}</CardContent></Card>
  {result&&<div className="flex items-start gap-3 rounded-2xl border bg-card p-4 shadow-soft">{result.ok?<CheckCircle2 className="mt-0.5 size-5 text-emerald-600"/>:<X className="mt-0.5 size-5 text-destructive"/>}<p className="text-sm leading-6">{result.text}</p></div>}
  <Tabs value={tab} onValueChange={setTab} className="space-y-4"><TabsList className="grid w-full max-w-md grid-cols-2 rounded-xl p-1"><TabsTrigger value="send" className="rounded-lg py-2.5"><Send className="mr-2 size-4"/>Due reminders</TabsTrigger><TabsTrigger value="history" className="rounded-lg py-2.5"><History className="mr-2 size-4"/>History</TabsTrigger></TabsList>
   <TabsContent value="send" className="space-y-5"><Card className="shadow-soft"><CardHeader><CardTitle>Due reminder template</CardTitle><CardDescription>Only purchase-day overview data belongs here. Supported placeholders: {'{name}'}, {'{records}'}, {'{totalDue}'}.</CardDescription></CardHeader><CardContent><textarea value={message} onChange={e=>setMessage(e.target.value)} className="min-h-48 w-full rounded-2xl border border-input bg-background p-4 text-sm leading-6 outline-none focus:border-primary focus:ring-2 focus:ring-primary/10"/></CardContent></Card>
    <Card className="shadow-soft"><CardHeader><CardTitle className="flex items-center gap-2"><Filter className="size-5"/>Customer search</CardTitle><CardDescription>Filter customers with outstanding dues before selecting who receives the reminder.</CardDescription></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div className="relative xl:col-span-2"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Name, mobile or village" value={filters.query} onChange={e=>setFilters({...filters,query:e.target.value})}/></div><select className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={filters.village} onChange={e=>setFilters({...filters,village:e.target.value})}><option value="all">All villages</option>{villages.map(v=><option key={v} value={v}>{v}</option>)}</select><Button variant={filters.dueOnly?"default":"outline"} className="rounded-full" onClick={()=>setFilters({...filters,dueOnly:!filters.dueOnly})}>Due only: {filters.dueOnly?"On":"Off"}</Button><Input type="number" min="0" placeholder="Minimum due" value={filters.minDue} onChange={e=>setFilters({...filters,minDue:e.target.value})}/><Input type="number" min="0" placeholder="Maximum due" value={filters.maxDue} onChange={e=>setFilters({...filters,maxDue:e.target.value})}/><Input type="date" value={filters.purchaseFrom} onChange={e=>setFilters({...filters,purchaseFrom:e.target.value})}/><Input type="date" value={filters.purchaseTo} onChange={e=>setFilters({...filters,purchaseTo:e.target.value})}/><Button variant={filters.whatsappOnly?"default":"outline"} className="rounded-full" onClick={()=>setFilters({...filters,whatsappOnly:!filters.whatsappOnly})}><Smartphone className="size-4"/> WhatsApp only: {filters.whatsappOnly?"On":"Off"}</Button><Button variant="outline" className="rounded-full" onClick={()=>setFilters(initialFilters)}>Reset filters</Button></div></CardContent></Card>
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-2"><Button variant="outline" className="rounded-full" onClick={()=>setSelectedIds(new Set(filteredCustomers.map(c=>c.id)))}>Select all</Button><Button variant="ghost" className="rounded-full" onClick={()=>setSelectedIds(new Set())}>Clear</Button></div><p className="text-sm text-muted-foreground">{filteredCustomers.length} customers · {selectedCustomers.length} selected</p></div>
    <div className="grid gap-3 lg:grid-cols-2">{filteredCustomers.map(c=>{const selected=selectedIds.has(c.id);return <Card key={c.id} className={selected?"border-primary shadow-soft":"shadow-soft"}><CardContent className="flex items-center gap-3 p-4"><Button size="sm" variant={selected?"default":"outline"} className="size-9 rounded-full p-0" onClick={()=>setSelectedIds(current=>{const next=new Set(current);next.has(c.id)?next.delete(c.id):next.add(c.id);return next})}>{selected?"✓":""}</Button><div className="min-w-0 flex-1"><p className="truncate font-semibold">{c.name}</p><p className="truncate text-xs text-muted-foreground">{c.mobile} · {c.village||"No village"}</p><p className="mt-1 text-xs">Current due <span className="font-semibold">{formatCurrency(c.currentDue)}</span></p></div><Button size="sm" variant="outline" className="rounded-full" onClick={()=>setPreviewCustomer(c)}><Eye className="size-4"/> Preview</Button></CardContent></Card>})}</div>
    <Card className="shadow-soft"><CardHeader><CardTitle>Overview preview</CardTitle><CardDescription>Every purchase day is shown with that day's amount and due, followed by the final total due.</CardDescription></CardHeader><CardContent>{selectedCustomers[0]?<div className="rounded-2xl border bg-muted/30 p-5"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Preview for {selectedCustomers[0].name}</p><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{resolveMessage(selectedCustomers[0])}</p></div>:<p className="text-sm text-muted-foreground">Select a customer to preview the reminder.</p>}<div className="mt-4 flex flex-col gap-3 border-t pt-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-muted-foreground">Live Meta WhatsApp connection.</p><Button className="rounded-full" disabled={!selectedCustomers.length||sending} onClick={()=>void send()}><Send className="size-4"/>{sending?"Sending…":`Send selected (${selectedCustomers.length})`}</Button></div></CardContent></Card>
   </TabsContent>
   <TabsContent value="history"><Card className="shadow-soft"><CardHeader><CardTitle>Delivery history</CardTitle><CardDescription>Actual WhatsApp deliveries recorded in Supabase.</CardDescription></CardHeader><CardContent>{!logs.length?<p className="py-8 text-center text-sm text-muted-foreground">No deliveries recorded yet.</p>:<div className="space-y-3">{logs.map(log=><div key={log.id} className="flex items-center gap-3 rounded-xl border p-4"><BellRing className="size-4 text-primary"/><div className="min-w-0 flex-1"><p className="font-medium">{log.reminderTitle}</p><p className="text-xs text-muted-foreground">{log.recipient} · {formatDate(log.sentAt)}</p></div><Badge variant="outline" className="rounded-full">{log.delivery}</Badge></div>)}</div>}</CardContent></Card></TabsContent>
  </Tabs>
  <CustomerPreviewDialog customer={previewCustomer} ledger={ledger} message={message} onMessageChange={setMessage} onClose={()=>setPreviewCustomer(null)} onSend={()=>void send()} sending={sending} buildOverview={buildOverview}/>
 </div>
}

function CustomerPreviewDialog({customer,ledger,message,onMessageChange,onClose,onSend,sending,buildOverview}:{customer:Customer|null;ledger:CustomerLedgerEntry[];message:string;onMessageChange:(v:string)=>void;onClose:()=>void;onSend:()=>void;sending:boolean;buildOverview:(c:Customer)=>string}){if(!customer)return null;const records=ledger.filter(e=>e.customerId===customer.id),days=new Set(records.filter(e=>e.entryType==="purchase").map(e=>e.date)).size,preview=message.replaceAll("{name}",customer.name).replaceAll("{records}",buildOverview(customer)).replaceAll("{totalDue}",formatCurrency(customer.currentDue));return <Dialog open={Boolean(customer)} onOpenChange={open=>!open&&onClose()}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{customer.name} — due overview</DialogTitle><DialogDescription>{customer.mobile} · {customer.village||"Village not recorded"}</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><Metric label="Current due" value={formatCurrency(customer.currentDue)} helper="Outstanding now"/><Metric label="Purchase days" value={String(days)} helper="Days with purchases"/></div><Separator/><div className="rounded-2xl border bg-muted/20 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Message</p><textarea value={message} onChange={e=>onMessageChange(e.target.value)} className="mt-3 min-h-44 w-full rounded-xl border border-input bg-background p-4 text-sm leading-6"/><div className="mt-3 rounded-xl bg-muted/60 p-4"><p className="whitespace-pre-wrap text-sm leading-6">{preview}</p></div></div><DialogFooter><Button variant="outline" className="rounded-full" onClick={onClose} disabled={sending}>Close</Button><Button className="rounded-full" disabled={sending} onClick={onSend}><Send className="size-4"/>{sending?"Sending…":"Edit & send"}</Button></DialogFooter></DialogContent></Dialog>}
function Metric({label,value,helper}:{label:string;value:string;helper:string}){return <Card className="shadow-soft"><CardContent className="p-4"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{helper}</p></CardContent></Card>}
