/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActivityLogsRouteImport } from './routes/admin.activity-logs'
import { Route as AdminAdvertisementsRouteImport } from './routes/admin.advertisements'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminBackupsRouteImport } from './routes/admin.backups'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSalesRouteImport } from './routes/admin.sales'
import { Route as AdminSearchRouteImport } from './routes/admin.search'
import { Route as AdminSecurityLogsRouteImport } from './routes/admin.security-logs'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin.customers.index'
import { Route as AdminCustomersNewRouteImport } from './routes/admin.customers.new'
import { Route as AdminCustomersCustomerIdIndexRouteImport } from './routes/admin.customers.$customerId.index'
import { Route as AdminCustomersCustomerIdEditRouteImport } from './routes/admin.customers.$customerId.edit'
import { Route as AdminKhataCustomersCustomerIdRouteImport } from './routes/admin.khata.customers.$customerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityLogsRoute = AdminActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdvertisementsRoute = AdminAdvertisementsRouteImport.update({
  id: '/advertisements',
  path: '/advertisements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupsRoute = AdminBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityLogsRoute = AdminSecurityLogsRouteImport.update({
  id: '/security-logs',
  path: '/security-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersNewRoute = AdminCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersCustomerIdIndexRoute =
  AdminCustomersCustomerIdIndexRouteImport.update({
    id: '/customers/$customerId/',
    path: '/customers/$customerId/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCustomersCustomerIdEditRoute =
  AdminCustomersCustomerIdEditRouteImport.update({
    id: '/customers/$customerId/edit',
    path: '/customers/$customerId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminKhataCustomersCustomerIdRoute =
  AdminKhataCustomersCustomerIdRouteImport.update({
    id: '/khata/customers/$customerId',
    path: '/khata/customers/$customerId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/advertisements': typeof AdminAdvertisementsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/security-logs': typeof AdminSecurityLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/customers/$customerId/edit': typeof AdminCustomersCustomerIdEditRoute
  '/admin/khata/customers/$customerId': typeof AdminKhataCustomersCustomerIdRoute
  '/admin/customers/$customerId/': typeof AdminCustomersCustomerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/advertisements': typeof AdminAdvertisementsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/security-logs': typeof AdminSecurityLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/customers/$customerId/edit': typeof AdminCustomersCustomerIdEditRoute
  '/admin/khata/customers/$customerId': typeof AdminKhataCustomersCustomerIdRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/advertisements': typeof AdminAdvertisementsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/security-logs': typeof AdminSecurityLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/customers/$customerId/edit': typeof AdminCustomersCustomerIdEditRoute
  '/admin/khata/customers/$customerId': typeof AdminKhataCustomersCustomerIdRoute
  '/admin/customers/$customerId/': typeof AdminCustomersCustomerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/activity-logs'
    | '/admin/advertisements'
    | '/admin/analytics'
    | '/admin/backups'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/search'
    | '/admin/security-logs'
    | '/admin/settings'
    | '/admin/'
    | '/admin/customers/new'
    | '/admin/customers/'
    | '/admin/customers/$customerId/edit'
    | '/admin/khata/customers/$customerId'
    | '/admin/customers/$customerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/activity-logs'
    | '/admin/advertisements'
    | '/admin/analytics'
    | '/admin/backups'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/search'
    | '/admin/security-logs'
    | '/admin/settings'
    | '/admin'
    | '/admin/customers/new'
    | '/admin/customers'
    | '/admin/customers/$customerId/edit'
    | '/admin/khata/customers/$customerId'
    | '/admin/customers/$customerId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/activity-logs'
    | '/admin/advertisements'
    | '/admin/analytics'
    | '/admin/backups'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/search'
    | '/admin/security-logs'
    | '/admin/settings'
    | '/admin/'
    | '/admin/customers/new'
    | '/admin/customers/'
    | '/admin/customers/$customerId/edit'
    | '/admin/khata/customers/$customerId'
    | '/admin/customers/$customerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity-logs': {
      id: '/admin/activity-logs'
      path: '/activity-logs'
      fullPath: '/admin/activity-logs'
      preLoaderRoute: typeof AdminActivityLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/advertisements': {
      id: '/admin/advertisements'
      path: '/advertisements'
      fullPath: '/admin/advertisements'
      preLoaderRoute: typeof AdminAdvertisementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backups': {
      id: '/admin/backups'
      path: '/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AdminBackupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/search': {
      id: '/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security-logs': {
      id: '/admin/security-logs'
      path: '/security-logs'
      fullPath: '/admin/security-logs'
      preLoaderRoute: typeof AdminSecurityLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/new': {
      id: '/admin/customers/new'
      path: '/customers/new'
      fullPath: '/admin/customers/new'
      preLoaderRoute: typeof AdminCustomersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$customerId/': {
      id: '/admin/customers/$customerId/'
      path: '/customers/$customerId'
      fullPath: '/admin/customers/$customerId/'
      preLoaderRoute: typeof AdminCustomersCustomerIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$customerId/edit': {
      id: '/admin/customers/$customerId/edit'
      path: '/customers/$customerId/edit'
      fullPath: '/admin/customers/$customerId/edit'
      preLoaderRoute: typeof AdminCustomersCustomerIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/khata/customers/$customerId': {
      id: '/admin/khata/customers/$customerId'
      path: '/khata/customers/$customerId'
      fullPath: '/admin/khata/customers/$customerId'
      preLoaderRoute: typeof AdminKhataCustomersCustomerIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivityLogsRoute: typeof AdminActivityLogsRoute
  AdminAdvertisementsRoute: typeof AdminAdvertisementsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBackupsRoute: typeof AdminBackupsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminSearchRoute: typeof AdminSearchRoute
  AdminSecurityLogsRoute: typeof AdminSecurityLogsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomersNewRoute: typeof AdminCustomersNewRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminCustomersCustomerIdEditRoute: typeof AdminCustomersCustomerIdEditRoute
  AdminKhataCustomersCustomerIdRoute: typeof AdminKhataCustomersCustomerIdRoute
  AdminCustomersCustomerIdIndexRoute: typeof AdminCustomersCustomerIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityLogsRoute: AdminActivityLogsRoute,
  AdminAdvertisementsRoute: AdminAdvertisementsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBackupsRoute: AdminBackupsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminSearchRoute: AdminSearchRoute,
  AdminSecurityLogsRoute: AdminSecurityLogsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomersNewRoute: AdminCustomersNewRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminCustomersCustomerIdEditRoute: AdminCustomersCustomerIdEditRoute,
  AdminKhataCustomersCustomerIdRoute: AdminKhataCustomersCustomerIdRoute,
  AdminCustomersCustomerIdIndexRoute: AdminCustomersCustomerIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
