/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActivityLogsRouteImport } from './routes/admin.activity-logs'
import { Route as AdminAdvertisementsRouteImport } from './routes/admin.advertisements'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminBackupsRouteImport } from './routes/admin.backups'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminRemindersRouteImport } from './routes/admin.reminders'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSalesRouteImport } from './routes/admin.sales'
import { Route as AdminSearchRouteImport } from './routes/admin.search'
import { Route as AdminSecurityLogsRouteImport } from './routes/admin.security-logs'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin.customers.index'
import { Route as AdminCustomersNewRouteImport } from './routes/admin.customers.new'
import { Route as AdminInventoryIndexRouteImport } from './routes/admin.inventory.index'
import { Route as AdminInventoryNewRouteImport } from './routes/admin.inventory.new'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminProductsPublishRouteImport } from './routes/admin.products.publish'
import { Route as AdminSuppliersIndexRouteImport } from './routes/admin.suppliers.index'
import { Route as AdminSuppliersSupplierIdRouteImport } from './routes/admin.suppliers.$supplierId'
import { Route as AdminCustomersCustomerIdIndexRouteImport } from './routes/admin.customers.$customerId.index'
import { Route as AdminCustomersCustomerIdEditRouteImport } from './routes/admin.customers.$customerId.edit'
import { Route as AdminKhataCustomersCustomerIdRouteImport } from './routes/admin.khata.customers.$customerId'
import { Route as AdminLedgerSuppliersSupplierIdRouteImport } from './routes/admin.ledger.suppliers.$supplierId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityLogsRoute = AdminActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdvertisementsRoute = AdminAdvertisementsRouteImport.update({
  id: '/advertisements',
  path: '/advertisements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupsRoute = AdminBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRemindersRoute = AdminRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityLogsRoute = AdminSecurityLogsRouteImport.update({
  id: '/security-logs',
  path: '/security-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersNewRoute = AdminCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryIndexRoute = AdminInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryNewRoute = AdminInventoryNewRouteImport.update({
  id: '/inventory/new',
  path: '/inventory/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsPublishRoute = AdminProductsPublishRouteImport.update({
  id: '/products/publish',
  path: '/products/publish',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuppliersIndexRoute = AdminSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuppliersSupplierIdRoute =
  AdminSuppliersSupplierIdRouteImport.update({
    id: '/suppliers/$supplierId',
    path: '/suppliers/$supplierId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCustomersCustomerIdIndexRoute =
  AdminCustomersCustomerIdIndexRouteImport.update({
    id: '/customers/$customerId/',
    path: '/customers/$customerId/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCustomersCustomerIdEditRoute =
  AdminCustomersCustomerIdEditRouteImport.update({
    id: '/customers/$customerId/edit',
    path: '/customers/$customerId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminKhataCustomersCustomerIdRoute =
  AdminKhataCustomersCustomerIdRouteImport.update({
    id: '/khata/customers/$customerId',
    path: '/khata/customers/$customerId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminLedgerSuppliersSupplierIdRoute =
  AdminLedgerSuppliersSupplierIdRouteImport.update({
    id: '/ledger/suppliers/$supplierId',
    path: '/ledger/suppliers/$supplierId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/advertisements': typeof AdminAdvertisementsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/security-logs': typeof AdminSecurityLogsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/inventory/new': typeof AdminInventoryNewRoute
  '/admin/products/publish': typeof AdminProductsPublishRoute
  '/admin/suppliers/$supplierId': typeof AdminSuppliersSupplierIdRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/suppliers/': typeof AdminSuppliersIndexRoute
  '/admin/customers/$customerId/edit': typeof AdminCustomersCustomerIdEditRoute
  '/admin/khata/customers/$customerId': typeof AdminKhataCustomersCustomerIdRoute
  '/admin/ledger/suppliers/$supplierId': typeof AdminLedgerSuppliersSupplierIdRoute
  '/admin/customers/$customerId/': typeof AdminCustomersCustomerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/advertisements': typeof AdminAdvertisementsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/security-logs': typeof AdminSecurityLogsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/inventory/new': typeof AdminInventoryNewRoute
  '/admin/products/publish': typeof AdminProductsPublishRoute
  '/admin/suppliers/$supplierId': typeof AdminSuppliersSupplierIdRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/inventory': typeof AdminInventoryIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/suppliers': typeof AdminSuppliersIndexRoute
  '/admin/customers/$customerId/edit': typeof AdminCustomersCustomerIdEditRoute
  '/admin/khata/customers/$customerId': typeof AdminKhataCustomersCustomerIdRoute
  '/admin/ledger/suppliers/$supplierId': typeof AdminLedgerSuppliersSupplierIdRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/advertisements': typeof AdminAdvertisementsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reminders': typeof AdminRemindersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/security-logs': typeof AdminSecurityLogsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/inventory/new': typeof AdminInventoryNewRoute
  '/admin/products/publish': typeof AdminProductsPublishRoute
  '/admin/suppliers/$supplierId': typeof AdminSuppliersSupplierIdRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/suppliers/': typeof AdminSuppliersIndexRoute
  '/admin/customers/$customerId/edit': typeof AdminCustomersCustomerIdEditRoute
  '/admin/khata/customers/$customerId': typeof AdminKhataCustomersCustomerIdRoute
  '/admin/ledger/suppliers/$supplierId': typeof AdminLedgerSuppliersSupplierIdRoute
  '/admin/customers/$customerId/': typeof AdminCustomersCustomerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/activity-logs'
    | '/admin/advertisements'
    | '/admin/analytics'
    | '/admin/backups'
    | '/admin/cms'
    | '/admin/payments'
    | '/admin/reminders'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/search'
    | '/admin/security-logs'
    | '/admin/'
    | '/admin/customers/new'
    | '/admin/inventory/new'
    | '/admin/products/publish'
    | '/admin/suppliers/$supplierId'
    | '/admin/customers/'
    | '/admin/inventory/'
    | '/admin/products/'
    | '/admin/suppliers/'
    | '/admin/customers/$customerId/edit'
    | '/admin/khata/customers/$customerId'
    | '/admin/ledger/suppliers/$supplierId'
    | '/admin/customers/$customerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/activity-logs'
    | '/admin/advertisements'
    | '/admin/analytics'
    | '/admin/backups'
    | '/admin/cms'
    | '/admin/payments'
    | '/admin/reminders'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/search'
    | '/admin/security-logs'
    | '/admin'
    | '/admin/customers/new'
    | '/admin/inventory/new'
    | '/admin/products/publish'
    | '/admin/suppliers/$supplierId'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/products'
    | '/admin/suppliers'
    | '/admin/customers/$customerId/edit'
    | '/admin/khata/customers/$customerId'
    | '/admin/ledger/suppliers/$supplierId'
    | '/admin/customers/$customerId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/activity-logs'
    | '/admin/advertisements'
    | '/admin/analytics'
    | '/admin/backups'
    | '/admin/cms'
    | '/admin/payments'
    | '/admin/reminders'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/search'
    | '/admin/security-logs'
    | '/admin/'
    | '/admin/customers/new'
    | '/admin/inventory/new'
    | '/admin/products/publish'
    | '/admin/suppliers/$supplierId'
    | '/admin/customers/'
    | '/admin/inventory/'
    | '/admin/products/'
    | '/admin/suppliers/'
    | '/admin/customers/$customerId/edit'
    | '/admin/khata/customers/$customerId'
    | '/admin/ledger/suppliers/$supplierId'
    | '/admin/customers/$customerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity-logs': {
      id: '/admin/activity-logs'
      path: '/activity-logs'
      fullPath: '/admin/activity-logs'
      preLoaderRoute: typeof AdminActivityLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/advertisements': {
      id: '/admin/advertisements'
      path: '/advertisements'
      fullPath: '/admin/advertisements'
      preLoaderRoute: typeof AdminAdvertisementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backups': {
      id: '/admin/backups'
      path: '/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AdminBackupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reminders': {
      id: '/admin/reminders'
      path: '/reminders'
      fullPath: '/admin/reminders'
      preLoaderRoute: typeof AdminRemindersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/search': {
      id: '/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security-logs': {
      id: '/admin/security-logs'
      path: '/security-logs'
      fullPath: '/admin/security-logs'
      preLoaderRoute: typeof AdminSecurityLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/new': {
      id: '/admin/customers/new'
      path: '/customers/new'
      fullPath: '/admin/customers/new'
      preLoaderRoute: typeof AdminCustomersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory/': {
      id: '/admin/inventory/'
      path: '/inventory'
      fullPath: '/admin/inventory/'
      preLoaderRoute: typeof AdminInventoryIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory/new': {
      id: '/admin/inventory/new'
      path: '/inventory/new'
      fullPath: '/admin/inventory/new'
      preLoaderRoute: typeof AdminInventoryNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/publish': {
      id: '/admin/products/publish'
      path: '/products/publish'
      fullPath: '/admin/products/publish'
      preLoaderRoute: typeof AdminProductsPublishRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers/': {
      id: '/admin/suppliers/'
      path: '/suppliers'
      fullPath: '/admin/suppliers/'
      preLoaderRoute: typeof AdminSuppliersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers/$supplierId': {
      id: '/admin/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/admin/suppliers/$supplierId'
      preLoaderRoute: typeof AdminSuppliersSupplierIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$customerId/': {
      id: '/admin/customers/$customerId/'
      path: '/customers/$customerId'
      fullPath: '/admin/customers/$customerId/'
      preLoaderRoute: typeof AdminCustomersCustomerIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$customerId/edit': {
      id: '/admin/customers/$customerId/edit'
      path: '/customers/$customerId/edit'
      fullPath: '/admin/customers/$customerId/edit'
      preLoaderRoute: typeof AdminCustomersCustomerIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/khata/customers/$customerId': {
      id: '/admin/khata/customers/$customerId'
      path: '/khata/customers/$customerId'
      fullPath: '/admin/khata/customers/$customerId'
      preLoaderRoute: typeof AdminKhataCustomersCustomerIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ledger/suppliers/$supplierId': {
      id: '/admin/ledger/suppliers/$supplierId'
      path: '/ledger/suppliers/$supplierId'
      fullPath: '/admin/ledger/suppliers/$supplierId'
      preLoaderRoute: typeof AdminLedgerSuppliersSupplierIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivityLogsRoute: typeof AdminActivityLogsRoute
  AdminAdvertisementsRoute: typeof AdminAdvertisementsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBackupsRoute: typeof AdminBackupsRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRemindersRoute: typeof AdminRemindersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminSearchRoute: typeof AdminSearchRoute
  AdminSecurityLogsRoute: typeof AdminSecurityLogsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomersNewRoute: typeof AdminCustomersNewRoute
  AdminInventoryNewRoute: typeof AdminInventoryNewRoute
  AdminProductsPublishRoute: typeof AdminProductsPublishRoute
  AdminSuppliersSupplierIdRoute: typeof AdminSuppliersSupplierIdRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminInventoryIndexRoute: typeof AdminInventoryIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminSuppliersIndexRoute: typeof AdminSuppliersIndexRoute
  AdminCustomersCustomerIdEditRoute: typeof AdminCustomersCustomerIdEditRoute
  AdminKhataCustomersCustomerIdRoute: typeof AdminKhataCustomersCustomerIdRoute
  AdminLedgerSuppliersSupplierIdRoute: typeof AdminLedgerSuppliersSupplierIdRoute
  AdminCustomersCustomerIdIndexRoute: typeof AdminCustomersCustomerIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityLogsRoute: AdminActivityLogsRoute,
  AdminAdvertisementsRoute: AdminAdvertisementsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBackupsRoute: AdminBackupsRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRemindersRoute: AdminRemindersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminSearchRoute: AdminSearchRoute,
  AdminSecurityLogsRoute: AdminSecurityLogsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomersNewRoute: AdminCustomersNewRoute,
  AdminInventoryNewRoute: AdminInventoryNewRoute,
  AdminProductsPublishRoute: AdminProductsPublishRoute,
  AdminSuppliersSupplierIdRoute: AdminSuppliersSupplierIdRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminInventoryIndexRoute: AdminInventoryIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminSuppliersIndexRoute: AdminSuppliersIndexRoute,
  AdminCustomersCustomerIdEditRoute: AdminCustomersCustomerIdEditRoute,
  AdminKhataCustomersCustomerIdRoute: AdminKhataCustomersCustomerIdRoute,
  AdminLedgerSuppliersSupplierIdRoute: AdminLedgerSuppliersSupplierIdRoute,
  AdminCustomersCustomerIdIndexRoute: AdminCustomersCustomerIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
