/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActivityLogsRouteImport } from './routes/admin.activity-logs'
import { Route as AdminAdvertisementsRouteImport } from './routes/admin.advertisements'
import { Route as AdminBackupsRouteImport } from './routes/admin.backups'
import { Route as AdminSecurityLogsRouteImport } from './routes/admin.security-logs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityLogsRoute = AdminActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdvertisementsRoute = AdminAdvertisementsRouteImport.update({
  id: '/advertisements',
  path: '/advertisements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupsRoute = AdminBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityLogsRoute = AdminSecurityLogsRouteImport.update({
  id: '/security-logs',
  path: '/security-logs',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/advertisements': typeof AdminAdvertisementsRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/security-logs': typeof AdminSecurityLogsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/advertisements': typeof AdminAdvertisementsRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/security-logs': typeof AdminSecurityLogsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/advertisements': typeof AdminAdvertisementsRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/security-logs': typeof AdminSecurityLogsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/activity-logs'
    | '/admin/advertisements'
    | '/admin/backups'
    | '/admin/security-logs'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/activity-logs'
    | '/admin/advertisements'
    | '/admin/backups'
    | '/admin/security-logs'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/activity-logs'
    | '/admin/advertisements'
    | '/admin/backups'
    | '/admin/security-logs'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity-logs': {
      id: '/admin/activity-logs'
      path: '/activity-logs'
      fullPath: '/admin/activity-logs'
      preLoaderRoute: typeof AdminActivityLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/advertisements': {
      id: '/admin/advertisements'
      path: '/advertisements'
      fullPath: '/admin/advertisements'
      preLoaderRoute: typeof AdminAdvertisementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backups': {
      id: '/admin/backups'
      path: '/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AdminBackupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security-logs': {
      id: '/admin/security-logs'
      path: '/security-logs'
      fullPath: '/admin/security-logs'
      preLoaderRoute: typeof AdminSecurityLogsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivityLogsRoute: typeof AdminActivityLogsRoute
  AdminAdvertisementsRoute: typeof AdminAdvertisementsRoute
  AdminBackupsRoute: typeof AdminBackupsRoute
  AdminSecurityLogsRoute: typeof AdminSecurityLogsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityLogsRoute: AdminActivityLogsRoute,
  AdminAdvertisementsRoute: AdminAdvertisementsRoute,
  AdminBackupsRoute: AdminBackupsRoute,
  AdminSecurityLogsRoute: AdminSecurityLogsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
